name: 'Sync Secrets Action'
description: 'Sync Repository, Dependabot and Codespaces secrets + variables between GitHub repositories'
author: 'cbrgm'

inputs:
  github-token:
    description: 'The GitHub token to use.'
    required: true
  target:
    description: 'The repository to sync secrets and variables to. Either this or query must be set, not both.'
    required: false
  query:
    description: 'GitHub search query to find repositories for batch processing. Either this or target must be set, not both.'
    required: false
  secrets:
    description: 'Secrets to sync.'
    required: false
  variables:
    description: 'Variables to sync.'
    required: false
  rate-limit:
    description: 'Enables rate limit checking.'
    default: "false"
    required: false
  max-retries:
    description: 'Maximum number of retries for operations. Must not be smaller than zero.'
    default: "3"
    required: false
  dry-run:
    description: 'Dry run. If true, no changes will be made.'
    default: "false"
    required: false
  prune:
    description: 'Prunes all existing secrets and variables not in the subset of those defined in this action.'
    default: "false"
    required: false
  environment:
    description: 'The GitHub environment to sync variables or secrets to. Use when targeting environment-specific secrets or variables.'
    required: false
  type:
    description: 'Type of the secrets to manage: actions, dependabot, or codespaces.'
    default: "actions"
    required: false

runs:
  using: 'docker'
  image: 'docker://ghcr.io/cbrgm/sync-secrets-action:v1'
  args:
    - --github-token=${{ inputs.github-token }}
    - --target
    - ${{ inputs.target }}
    - --query
    - ${{ inputs.query }}
    - --environment
    - ${{ inputs.environment }}
    - --rate-limit
    - ${{ inputs.rate-limit }}
    - --max-retries
    - ${{ inputs.max-retries }}
    - --dry-run=${{ inputs.dry-run }}
    - --prune=${{ inputs.prune }}
    - --type=${{ inputs.type }}
    - --secrets
    - ${{ inputs.secrets }}
    - --variables
    - ${{ inputs.variables }}

branding:
  icon: 'lock'
  color: 'green'
