FROM i386/alpine:3.19 AS build
RUN apk add --no-cache ca-certificates

FROM scratch

ENTRYPOINT ["/usr/bin/sync-secrets-action"]

COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

COPY bin/sync-secrets-action /usr/bin/sync-secrets-action
